config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	# protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user,only: [:edit, :update, :destroy]

  def show
	@book_detail = Book.find(params[:id])
	@user = @book_detail.user
	@book = Book.new
  end

  def index
	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
	@book = Book.new
	@user = User.find(current_user.id)  
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(book)
    else
      @book = book
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(book)
    else
      @book = book
      render :edit
    end
  end

  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  def ensure_correct_user
    book = Book.find(params[:id])
    if book.user_id != current_user.id
      redirect_to books_path
    end
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, {only: [:edit, :update]}

  def show
  	@user = User.find(params[:id])
  	@books = @user.books.all
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
	@user = current_user  
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if  user.update(user_params)
      flash[:notice] = "You have creatad book successfully."
      redirect_to user_path(user)
    else
      @user = user
      render :edit
    end
  end

  def ensure_correct_user
    user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
#    def baria_user
#   	unless params[:id].to_i == current_user.id
#   		redirect_to user_path(current_user)
#   	end
#    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<% if flash[:notice] %>
	<p class="green"><%= flash[:notice] %></p>
<% end %>

    <% if @book.errors.any? %> 
      <%= @book.errors.count %>  error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>

<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
	<p class="green"><%= flash[:notice] %></p>
<% end %>

    <% if @book.errors.any? %> 
      <%= @book.errors.count %>  error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<p class="green"><%= flash[:notice] %></p>
<% end %>

    <% if @book.errors.any? %> 
      <%= @book.errors.count %>  error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile' %>

		<h2>New book</h2>
		<%= render 'books/newform' %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@user) do %>
						<%= attachment_image_tag @user,:profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg",size: "100x100" %>
						<%= @user.name %>
						<% end %>
					</td>
					<td>
						<%= link_to book_path(@book_detail) do %> 
						<%= @book_detail.title %>
						<% end %>
					</td>
					<td>
						<%= @book_detail.body %>
					</td>
					  <% if @user == current_user %>
						<td><%= link_to "Edit",edit_book_path(@book_detail), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",book_path(@book_detail), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					  <% end %>
				</tr>
			</table>

	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to(content_tag(:span, " logout", class: "glyphicon glyphicon-log-out"),  destroy_user_session_path, method: :delete) %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="body container">
      <%= yield %>
    </div>

    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>
  </body>
</html>

app/views/users/_profile.html.erb
        <%= attachment_image_tag @user, :profile_image, :fill, 100,100 , format: 'jpeg', class: "pull-left profile-img", fallback:"no_image.jpg" %>
        <table class="table">
          <thead>
          </thead>
          <tbody>
            <tr>
              <td>name</td>
              <td><%= @user.name %></td>
            </tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tbody>
        </table>

        <div class="row">
            <% if @user == current_user %>
              <%= link_to(content_tag(:span, "", class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_15043"), edit_user_path(@user)) %>
            <% else %>
              <%= link_to(content_tag(:span, "", class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_15043"), user_path(current_user)) %>
            <% end %>
        </div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit "Update User" %>
</div>

<% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
	<p class="green"><%= flash[:notice] %></p>
<% end %>

    <% if @book.errors.any? %> 
      <%= @book.errors.count %>  error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>

<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<h2>Users</h2>
	<!--users一覧 -->
	<div class="col-xs-9">
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<!--users一覧 -->
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<p class="green"><%= flash[:notice] %></p>
<% end %>

    <% if @book.errors.any? %> 
      <%= @book.errors.count %>  error prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>

<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<h2>Books</h2>
	<!--books一覧 -->
	<div class="col-xs-9">
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<!--books一覧 -->
</div>